language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-28.0.2
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-v7a-addon-google_apis-google-27

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
    - echo y | sdkmanager "platforms;android-27"
    - echo y | sdkmanager "build-tools;27.0.3"
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
    - chmod +x gradlew
    - ./gradlew dependencies || true

install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-27.0.3
  - echo y | android update sdk -u -a -t android-27
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository

script:
  - ./gradlew clean build -Pbuild=dev --stacktrace
